CREATE TABLE IF NOT EXISTS ips(ip BIGINT NOT NULL PRIMARY KEY,count INTEGER,block SMALLINT,last INT);
CREATE TABLE IF NOT EXISTS details(id serial PRIMARY KEY,src BIGINT,dst BIGINT,port INTEGER,note varchar(255), time INT);
